{% set name = "difftastic" %}
{% set version = "0.62.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Wilfred/{{ name }}/archive/{{ version }}.tar.gz
  sha256: ef69a23c6e3b9697d84ea5be158e8cb6d7482f49fc91cf4f9c7416bd48301260

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - cargo-bundle-licenses

test:
  commands:
    - difft --help

about:
  home: https://github.com/Wilfred/difftastic
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Diff that understands syntax
  dev_url: https://github.com/Wilfred/difftastic

extra:
  recipe-maintainers:
    - danielnachun
