{% set name = "difftastic" %}
{% set version = "0.64.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Wilfred/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 54c7c93309ff9a2cbe87153ac1d16e80bacac4042c80f6b7206e9b71a6f10d0b

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - cargo-bundle-licenses

test:
  commands:
    - difft --help

about:
  home: https://github.com/Wilfred/difftastic
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Diff that understands syntax
  dev_url: https://github.com/Wilfred/difftastic

extra:
  recipe-maintainers:
    - danielnachun
