{% set name = "difftastic" %}
{% set version = "0.67.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Wilfred/{{ name }}/archive/{{ version }}.tar.gz
  sha256: a6a15d6ca9f9ab7c034d1770417d1829deb3fbe9dcf4731b9cba867e50e78437

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - cargo-bundle-licenses
    - make

test:
  commands:
    - difft --help

about:
  home: https://github.com/Wilfred/difftastic
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Diff that understands syntax
  dev_url: https://github.com/Wilfred/difftastic

extra:
  recipe-maintainers:
    - danielnachun
