schema_version: 1

context:
  name: difftastic
  version: 0.65.0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/Wilfred/${{ name }}/archive/${{ version }}.tar.gz
  sha256: 59462f69e2cedfdc1bee4fd0da48fe9a7ae635cdb6818c1a300b31c0b146d4b8

build:
  number: 0
  skip: win

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses
    - make

tests:
  - script:
      - difft --help

about:
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Diff that understands syntax
  homepage: https://github.com/Wilfred/difftastic
  repository: https://github.com/Wilfred/difftastic

extra:
  recipe-maintainers:
    - danielnachun

